---
- name: 各ユーザのパスワードupdate
  uri: >
    method=POST
    url='http://127.0.0.1:80/{{item.value.id}}'
    status_code=200
    body='{"user":{"password":"{{item.value.password}}"}}'
  ignore_errors: yes
  with_dict: some.users
  tags: update_password
