- name: install python packages
  pip: name={{item}} state=present
  with_items:
    - pymysql
  register: pip_install_common_package
  until: pip_install_common_package|success
  sudo: true
  tags: pip
  retries: 3
  delay: 90
